### ISSUE TITLE
Unable to create a new BingApiKey

### ISSUE THREAD

**Issue by harishmohanraj** [airtai/fastagency#210]
File "fastagency/app.py", line 28, in validate_model
    Registry.get_default().validate(type, name, model)
  File "fastagency/models/registry.py", line 183, in validate
    return model_type(**model)
           ^^^^^^^^^^^^^^^^^^^
TypeError: Can't instantiate abstract class BingAPIKey with abstract method create_autogen

**Comment by kumaranvpl** [comment]
Fixed - https://github.com/airtai/fastagency/pull/213
