### ISSUE TITLE
Bug: wrong type of key selected when pressing create new secret on OpenAI LLM

### ISSUE THREAD

**Issue by davorrunje** [airtai/fastagency#585]
<img width="1323" alt="Screenshot 2024-07-19 at 11 49 43" src="https://github.com/user-attachments/assets/2f222507-711d-45f9-b253-38b069b6c7f9">
<img width="1322" alt="Screenshot 2024-07-19 at 11 49 20" src="https://github.com/user-attachments/assets/ff3de669-8e91-481e-8e87-7162360673fe">

**Comment by harishmohanraj** [comment]
Do not bold the last option
